services:
    db:
        image: postgres:16-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: dbtyper_example
        ports:
            - "54333:5432"
        volumes:
            - dbtyper_example_pgdata:/var/lib/postgresql/data

volumes:
    dbtyper_example_pgdata:
