services:
    db:
        image: postgres:16-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: dbtyper_nest_example
        ports:
            - "54334:5432"
        volumes:
            - dbtyper_nest_example_pgdata:/var/lib/postgresql/data

volumes:
    dbtyper_nest_example_pgdata:
